spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/moviedb?currentSchema=movie}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: false

springdoc:
  packages-to-scan:
    - com.api.movies.controller